version: "3.8"

services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=my-bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-secret-token
    restart: unless-stopped

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: esp32-dashboard
    ports:
      - "8501:8501"
    volumes:
      - ./data/sensor_data.csv:/app/data/sensor_data.csv
    depends_on:
      - influxdb
    restart: unless-stopped

volumes:
  influxdb_data:
